[WIP]ChatSpaceのDB設計
gontabi/DataBaseDesignSample pull request #1
Opened 2019-02-18 10:03 UTC by gontabi

# WHAT
DB設計を作成

# WHY
サービスに必須のため

2019-02-18 10:30 UTC, ghost requested changes
全体的にDB設計のカリキュラムの理解不足と見受けられますので、今一度カリキュラムの復習をお願い致します。
その際にわからない点などあれば、積極的にメンターに質問をして、わからないところを解消してください。

2019-02-18 10:30 UTC, hiroki5123 commented on README.md
> +|group|string|null: false, foreign_key: true|
nameでいいと思います

2019-02-18 10:56 UTC, gontabi commented
ご確認ありがとうございます。
修正しました。
確認お願いします。

2019-02-18 10:59 UTC, TOMARUMARU reviewed
アソシエーションと外部キーについて復習する、又はよく調べてみてください。理解が甘いようです。
よくわからなければメンターに尋ねましょう

2019-02-18 12:01 UTC, gontabi commented
ご確認ありがとうございます。
カリキュラムを読み直し、修正しました。
確認お願いします。

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +|name|string|null: false|
user名で検索をかけるのでindexを貼りましょう。uniqueもつけましょう。それぞれ何か忘れてしまっていましたら、軽く復習して思い出しましょう

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +- has_many :messages, though: :members
messagesとは1対多です。

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +- has_many :messages, though: :members
messagesとは1対多です。

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +|body|text|null: false|
テキスト、画像それぞれどちらかで送信できる仕様なので、null:falseは外しましょう

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +|image|string|null: false|
同様です

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-02-18 12:08 UTC, TOMARUMARU commented on README.md
> +- has_many :members
membersとのアソシエーションは組む必要はありません

2019-02-19 06:32 UTC, gontabi commented
修正しました。
ご確認お願いします。

2019-02-19 06:32 UTC, miyagit approved these changes
LGTMです。

2019-02-19 06:34 UTC, gontabi commented on README.md
> +- has_many :messages, though: :members
お世話になります。
この部分がよくわかっていないので、質問なのですが、
user 1 :  messages 多
の考えで上記のプログラムになったのですが、考え的に間違っているでしょうか？
宜しくお願いします。

2019-02-19 06:38 UTC, gontabi commented
ありがとうございました。

2019-02-19 06:38 UTC, merged